version: '3.5'

services:
  fast_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_microservice
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/fastapi-docker

    networks:
      - django
networks:
  django:
    driver: bridge
    external: true
    name: django